USE sd3;

CREATE TABLE IF NOT EXISTS `topics` (
    `Id` INT PRIMARY KEY AUTO_INCREMENT,
    `Title` VARCHAR(200) NOT NULL,
    `Description` TEXT NOT NULL,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `AuthorId` VARCHAR(36) NOT NULL,
    `Active` BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (`AuthorId`) REFERENCES `users`(`id`)
);