USE sd3;

CREATE TABLE IF NOT EXISTS `ideas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Content` TEXT NOT NULL,
  `TopicId` INT NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`Id`),
  FOREIGN KEY (`TopicId`) REFERENCES `topics`(`Id`) ON DELETE CASCADE
);
