USE sd3;

CREATE TABLE IF NOT EXISTS `votes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdeaId` INT NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`Id`),
  FOREIGN KEY (`IdeaId`) REFERENCES `ideas`(`Id`) ON DELETE CASCADE
);
