version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: sd3db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sd5
      MYSQL_DATABASE: sd3
    ports:
      - "3307:3306"
    volumes:
      # MySQL ejecuta estos scripts en orden alfabético al iniciar
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./topics.sql:/docker-entrypoint-initdb.d/02_topics.sql
      - ./ideas.sql:/docker-entrypoint-initdb.d/03_ideas.sql
      - ./votes.sql:/docker-entrypoint-initdb.d/04_votes.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10